[alembic]
# Ruta al script de migración de Alembic
script_location = alembic

# Prefijo de las revisiones de migración
# file_template = %%(rev)s_%%(slug)s

# Zona horaria (dejar vacío para UTC local del sistema)
# timezone =

# Truncar longitudes de slug
# truncate_slug_length = 40

# Establecer en 'true' para ejecutar el entorno en modo offline
# revision_environment = false

# Establecer en 'true' para almacenar la versión de la BD en cada revisión
# sourceless = false

# Número de versión de la BD
version_path_separator = os

# Usar path separator de OS
# version_path_separator = :

sqlalchemy.url = driver://usuario:password@localhost/consultar_campo

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
